name: MAUI Unit Tests

on:
  push:
    branches:
      - main
      - dev
      - infra/runner-toevoegen
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Haal de repository op
        uses: actions/checkout@v4

      - name: Installeer .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Installeer MAUI workloads
        run: dotnet workload install maui

      - name: Herstel afhankelijkheden
        run: dotnet restore

      - name: Bouw de applicatie voor Windows
        run: dotnet build --configuration Release --no-restore -f net8.0-windows10.0.19041.0

      - name: Voer unit tests uit voor Windows
        run: dotnet test --configuration Release --no-restore --no-build -f net8.0-windows10.0.19041.0 --verbosity normal
